# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/91e5cae7-afb0-4b2b-8526-a743a8626e2a";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "discard=async" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/91e5cae7-afb0-4b2b-8526-a743a8626e2a";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "discard=async" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/91e5cae7-afb0-4b2b-8526-a743a8626e2a";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "discard=async" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/b7e17e31-ac83-4a32-b9a2-4b07d73eebc1";
      fsType = "btrfs";
      options = [ "compress=zstd" "discard=async" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3D7B-6AE4";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e8f18d65-f813-49c5-8551-ba3b586a9e71"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
